language: ruby
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
rvm:
- 2.4.1
services:
- postgresql
before_install: gem install bundler -v 2.0.2
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: "jP/C69vbJJ+YWIlFPplJM8oG1sc10i53i5FIpD03jdMamAuPaFQIUHXc1d31HmXJ1IF5HVq5U7gagK1oU3FBdNuL9em2Koq3/iXhDya1AQml/wGS/LcDBQ5lQtm37klZXNLQgWzI5QB2Ao+kYdIgDWrRZyE5PlgruXDXu1OK6dkLJbjvQZKyhN7IUjPX/5fMS7TDb1BaOWRi5qViKNS14NGKRJDtRHRygL0QW7F3aNgTMFmhftQE0MNR6yYTycuJbhLjLlA32YtxDbUPLqQLNz4cHIdA9ZvP+nkXhO6yLmT5HU06obDflCkFn6JQKxZJaZfO2XOZxbcwRBKMKllLzPYQUUzGGAei0lCws3vOiTuv+Zw+1IP8icVGgQFnIazesA70TSeWvTcKdfERwzMAlN+L6AmvPSEWzDN+Xp+MGZSD6+BBym+AbGHummg5x/dw0mqBgtg/k34LNV2fe31PFU+QtHGdQz3mNjR2y05hspCnC3IS4ekDAhu/ConwY90OGpUZcNtLswrY90mQfkh+Zg4TvO8OMrriis0vFKy+wu8M8KTND8BDcy/jDclsXWs0cipGCjeov8J8bAGRHwPDK9qyuP28FNXrQHe+IcQzQg+06oaAkCtLvRZRGpu6AnFwJTLjVQr6BkiUQwg4igdfZq8BMrX9ANyhrWucdE6afKA="
    app: ican2-be-rails
      on:
        repo: cjkelling/ican2_be
