language: ruby
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
rvm:
- 2.4.1
services:
- postgresql
before_install: gem install bundler -v 2.0.2
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
