language: ruby
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
rvm:
- 2.4.1
services:
- postgresql
before_install: gem install bundler -v 2.0.2
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Nq18uTIxIghiFJw6B84GR+gy5oTjb/gKbrfbOxqa/EnKqV/tp0vud+7lGlj3J4MTkusuGNXfDbxW8PPOv0k3IRuAI6zuVRm3LW0jZqvuWQlM0cj0B6s+nsl/2hrZUqIFzUrZjVyb4hdMhSAf4EKC6YgFkdcjLGWDBmpUci6p+t9za2e7iuu96SgXhDILlyJX5P6ovUV7xtMCviLbQaDcXAzyMFyHyUYJEd2Yg6IZnhFwf8rAAYI8iK45HnBixv34ifemptUdcy+HM+NYq+Vz/11gi3J5Fu5JnGc6ydqafT3gGJy6L2r1+yM2J8zc9bdRvAha02cWEKcli5DL5tZ35AElhcgOzFwWfpR5RKIO+wL/U09NcvW16GbJyvPpamBxmmhgE7RYmLG8IYCtWUidAxvJe4GxLFeqabBTc4WCKk0TLnNSf4DKNLsboksHR1Om0WyWf+g+trDsJQXK9mpEWhviky7N5+8o3jar95te++1ypUKGVBylRVVdDKYvbl7lKdPHXup+6xWcuDm4zkboEQ1odBpZ5td3TbmSe4eUEQ6HvcOpmbh0zNUk/XEZ8UzidBrRlj5M0ZGQ1WVWpnMdqr9UYKYmmFxZqqYv67aNZn4I7e8UhgqIPGK7SGAs52GV9nqY+jc34WIGKiZsR+qnrpeSwZ9O2gQxEXybCR9yxY8=
  app: ican2
  on:
    repo: cjkelling/ican2_be
